[build]
  command = "npm build"
[[headers]]
  for = "*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'self';default-src 'none'; font-src https://fonts.googleapis.com; img-src *; object-src 'none'; script-src https://code.jquery.com https://cdnjs.cloudflare.com https://www.gstatic.com https://cdn.tiny.cloud; style-src *"
    X-Content-Type-Options = "nosniff"
