[build]
  command = "npm build"
[[headers]]
  for = "*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' *.googleapis.com cdnjs.cloudflare.com code.jquery.com;"
    X-Content-Type-Options = "nosniff"
