const string_error = "<i class = 'material-icons'> error </ i> An unexpected problem has been encountered: ";
const string_group_createChannel = "Creating a conversation";
const string_default_name = "Conversation #";
const string_createChannel_success = "Conversation has been created.";
const string_group_createChannelWindow = "Window for creating a conversation";
const string_you = "(You)";
const string_createChannelWindow_success = "The loading of the list of users has finished.";
const string_group_editChannelWindow = "Conversation properties window";
const string_everyone = "<i>Everyone</i>";
const string_permission = {
"ADMIN": "You are administrator",
"MEMBER": "You are member",
"GUEST": "You are guest"
};
const string_permissions = {
	"ADMIN": "Administrator",
	"MEMBER": "Member",
	"GUEST": "Muted"
};
const string_editChannelWindow_success = "Information about permissions loaded.";
const string_group_renameChannel = "Changing the conversation name #";
const string_new_name = "New name:";
const string_renameChannel_success = "The name of the conversation has been changed to:";
const string_group_openChannelSelector = "Conversation selector";
const string_selector = "Conversations";
const string_openChannelSelector_success = "Loading available conversations was successful.";
const string_group_notifyReceivers = "Send notifications";
const string_conversation = "Conversation:";
const string_sender = "Sender:";
const string_group_sendMessage = "Sending messages";
const string_sendMessage_success = "The message has been sent.";
const string_sendMessage_empty = "Sending empty messages is not allowed.";
const string_group_count = "Statistics update";
const string_count_success = "Changed statistic";
const string_group_adminOptions = "Administrative options";
const string_adminOptions_show = "Administrative options shown.";
const string_adminOptions_hide = "Administrative options hidden.";
const string_group_discovery = "Tutorial";
const string_discovery_not_discovered = "The user has not yet discovered the function:";
const string_discovery_discovered = "The user has discovered the function:";
const string_group_actionSend = "Panel for sending messages";
const string_actionSend_show = "The message sending panel has been shown.";
const string_actionSend_hide = "The panel for sending messages has been hidden.";
const string_group_checkPerms = "Checking permissions";
const string_your_permissions = "Your permissions:";
const string_access_denied = "You do not have access to this conversation.";
const string_group_scrollToBottom = "Scrolling";
const string_scrollToBottom_messages = "Scrolling the message window to:";
const string_scrollToBottom_body = "Scroll the entire page to:";
const string_group_timeAgo = "Relative time";
const string_just_now = "Just now";
const string_minutes_ago = "minute(s) ago";
const string_hours_ago = "hour(s) ago";
const string_group_ranking = "Global ranking";
const string_group_getUserInfo = "User profile";
const string_reputation = "Reputation:";
const string_sent_count = "Sent messages:";
const string_deleted_count = "Deleted messages:";
const string_user_online = "<span class = 'green-text'>Online</span>";
const string_user_offline = "Last activity:";
const string_everyone_info = "(all current and new users)";
const string_group_getAuthorData = "Message information";
const string_account_deleted = "<i>Account deleted</i>";
const string_group_sendVote = "Reaction";
const string_sendVote_success = "The reaction has been sent.";
const string_sendVote_removed = "The reaction has been removed.";
const string_group_undo = "Undo delete messages";
const string_undo_success = "Message restored:";
const string_group_removeMessage = "Deleting messages";
const string_removeMessage_success = "Message # removed";
const string_undo = "Undo";
const string_group_contextMenu = "Message options";
const string_no_voting_for_self = "You can not post reactions to your own messages.";
const string_reaction_positive = "You have reacted positively.";
const string_reaction_negative = "You have reacted negatively.";
const string_group_autoUpdate = "Update messages";
const string_empty_conversation = "<p class = 'center'>This conversation is empty...</ p>";
const string_group_joinChannel = "Join conversation";
const string_joinChannel_success = "Joined conversation #";
const string_group_setTitle = "Change window title";
const string_group_settings = "Application settings";
const string_group_changeNick = "Changing nick";
const string_changeNick_success = "The username has been changed successfully.";
const string_group_changePassword = "Change password";
const string_changePassword_success = "The account password has been successfully changed.";
const string_group_deleteAccount = "Account deletion";
const string_group_changeEmail = "Changing the email address";
const string_changeEmail_success = "The e-mail address has been successfully changed.";
const string_group_changeAvatar = "Changing the profile photo";
const string_upload_paused = "waiting for the network...";
const string_upload_running = "uploading in progress...";
const string_changeAvatar_success = "Avatar has been successfully changed.";
const string_group_resetAvatar = "Reset profile photo";
const string_resetAvatar_success = "Default profile picture restored.";
const string_group_getAccountConfig = "Account configuration";
const string_getAccountConfig_success = "The basic configuration of the account has been completed.";
const string_group_onTokenRefresh = "Refreshing the WebPush token";
const string_group_onMessage = "Incoming message";
const string_push_permission_granted = "Notifications are allowed.";
const string_push_permission_denied = "Notifications are blocked.";
const string_push_token_unavaiable = "The WebPush token is unavailable.";
const string_not_logged_in = "User is not logged in.";
const string_group_register = "Registration";
const string_register_empty_nick = "You must enter a username.";
const string_group_login = "Login";
const string_group_logOut = "Logout";
const string_group_password_reset = "Password recovery";
const string_password_reset_success = "Recovery instructions have been sent to:";
const string_group_changeRankWindow = "User rank change window";
const string_group_changeRank = "Changing rank of user ";
const string_group_kickUserWindow = "User kick window";
const string_group_kickUser = "Kick";
const string_group_kickUser_success = " was kicked from this conversation.";
const string_addUsers = "Add users...";
const string_group_addUsersWindow = "Add users window";
const string_group_addUsers = "Adding users";
const string_addUsers_success = " was added to this conversation.";